### ISSUE TITLE
dind-dotnet-core-runner

### ISSUE THREAD

**Issue by inongogo** [rudolfdobias/firefly#1]
Hi,
I was wondering if you still have the repo [dind-dotnet-core-runner](https://github.com/rudolfdobias/dind-dotnet-core-runner) somewhere. The link is dead and it looked like the exact thing I would need for my project if you were willing to share.

Thanks!

**Comment by rudolfdobias** [comment]
Hi,
sure thing. I put all the images into one repo https://github.com/rudolfdobias/dockers. You might be interested in the dind-deploy.net.rc4 version. If you'd like newer .net core package, just replace line 11 (`dotnet-dev-1.0.0-rc4-004771`) with another one (ie `dotnet-dev-1.0.4`), it should work.

Example of usage in gitlab ci pipeline:

```
...

variables:
  PUSH_TAG: <PATH_TO_YOUR_CONTAINER_REGISTRY>:$CI_BUILD_REF_NAME-$CI_BUILD_TAG-$CI_BUILD_REF

build:
  stage: build
  services:
    - docker:dind
  script:
    - dotnet restore
    - dotnet publish -c Release
    - eval $(aws ecr get-login --region eu-central-1)
    - docker build -t api-build .
    - docker tag api-build $PUSH_TAG
    - docker push $PUSH_TAG

deployment-master:
  stage: deploy-master
  script:
    - ecs-deploy -c <YOUR_CLUSTER> -n <YOUR_SERVICE> -i $PUSH_TAG -r eu-central-1
  environment: Master
  dependencies:
    - build
  only:
    - master

...
```

For more reference, the ecs-deploy command is from here https://github.com/silinternational/ecs-deploy

Good lock
